#*------------------------*#
#*  udiskie's config.yml  *#
#*------------------------*#

program_options:
  tray: auto
  notify: true
  automount: false
  file_manager: 'kitty lf'
  password_prompt: 'builtin:gui'
 
notifications:
  device_added: 5
  device_unlocked: 5
  device_mounted: 5
  device_unmounted: 3
  device_removed: false

notification_actions:
  device_added: [mount, unlock]
  device_mounted: [browse]
