[menu]
executable = "fuzzel"
args = [
    '--match-mode=exact',
    '--no-run-if-empty',
    '--lines=10',
    '--minimal-lines',
    '--width=42',
    '--line-height=25',
    '--dmenu',
    '--placeholder={prompt}',
]

[format]
output_format = 'Output: {name}'
workspace_format = 'Workspace: {name}'
container_format = 'Container {layout:{:21.21}…} [W:{workspace_name}]'
window_format = "{name:{:31.31}…} [W:{workspace_name}]\u0000icon\u001f{app_icon}"
icon_dirs = [
    "~/.local/share/icons/hicolor/256x256/apps",
    "/usr/share/icons/hicolor/scalable/apps",
    "/usr/share/icons/hicolor/512x512/apps",
    "/usr/share/icons/hicolor/256x256/apps",
    "/usr/share/icons/hicolor/192x192/apps",
    "/usr/share/icons/hicolor/128x128/apps",
    "/usr/share/icons/hicolor/64x64/apps",
    "/usr/share/icons/hicolor/48x48/apps",
    "/usr/share/icons/hicolor/32x32/apps",
    "/usr/share/pixmaps",
]

[layout]
auto_tile = false

[focus]
lockin_delay = 750

[misc]
seq_inhibit = false

[swaymsg_commands]
include_predefined = true
