[menu]
executable = "fzf-popup"
args = [
    '50x12',
    '--no-multi',
    '--margin=0,1,1',
    '--exact',
    '--no-info',
    '--cycle',
    '--delimiter=\t',
    '--tabstop=1',
    '--nth=2..',
    '--input-label= {prompt} ',
    '--input-border=horizontal',
]

[format]
output_format = "Output:\t{name}"
workspace_format = "Workspace:\t{name}"
container_format = "[{workspace_name}]\t{layout} Container"
window_format = "[{workspace_name}]\t{app_name}  ─  {name}"
icon_dirs = [
]

[layout]
auto_tile = false

[focus]
lockin_delay = 750

[misc]
seq_inhibit = false

[swaymsg_commands]
include_predefined = true
