#*------------------------*#
#*  ncspot's config.toml  *#
#*------------------------*#

backend = "pulseaudio"

# TUI settings
use_nerdfont = true
flip_status_indicators = true
initial_screen = "library"
statusbar_format = "%artists - %title"

# Playback settings
volnorm = false
bitrate = 320
gapless = false
shuffle = false
repeat = "off"
playback_state = "Stopped"

[track_format]
left = "%title"
center = "%artists [%album]"
right = "%saved %duration"

[theme]
background = "default"
primary = "#d8d2d8"
secondary = "#dba5e5"
title = "#a86df2"
playing = "#bd93f9"
playing_selected = "#d0b3fa"
playing_bg = "default"
highlight = "#f4ebf4"
highlight_bg = "#3b3b55"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "2d2d2d"
statusbar_progress = "#a079d8"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "#231c23"
search_match = "#ff79c6"

[keybindings]
# Disable defaults
"F1" = "noop"
"F2" = "noop"
"F3" = "noop"
"F8" = "noop"
# Navigation
"Alt+1" = "focus library"
"Alt+2" = "focus queue"
"Alt+3" = "focus search"
"g" = "move top"
"G" = "move bottom"
# Playback
"+" = "volup 5"
"-" = "voldown 5"
